package com.lewis.base.entity;

import java.io.Serializable;

public class Srecord implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column srecord.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column srecord.sid
     *
     * @mbg.generated
     */
    private Integer sid;
    private Stucent stucent;
    private Kecheng kecheng;

    public Stucent getStucent() {
        return stucent;
    }

    public void setStucent(Stucent stucent) {
        this.stucent = stucent;
    }

    public Kecheng getKecheng() {
        return kecheng;
    }

    public void setKecheng(Kecheng kecheng) {
        this.kecheng = kecheng;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column srecord.kid
     *
     * @mbg.generated
     */
    private Integer kid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column srecord.time
     *
     * @mbg.generated
     */
    private String time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table srecord
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column srecord.id
     *
     * @return the value of srecord.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column srecord.id
     *
     * @param id the value for srecord.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column srecord.sid
     *
     * @return the value of srecord.sid
     *
     * @mbg.generated
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column srecord.sid
     *
     * @param sid the value for srecord.sid
     *
     * @mbg.generated
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column srecord.kid
     *
     * @return the value of srecord.kid
     *
     * @mbg.generated
     */
    public Integer getKid() {
        return kid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column srecord.kid
     *
     * @param kid the value for srecord.kid
     *
     * @mbg.generated
     */
    public void setKid(Integer kid) {
        this.kid = kid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column srecord.time
     *
     * @return the value of srecord.time
     *
     * @mbg.generated
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column srecord.time
     *
     * @param time the value for srecord.time
     *
     * @mbg.generated
     */
    public void setTime(String time) {
        this.time = time == null ? null : time.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table srecord
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", sid=").append(sid);
        sb.append(", kid=").append(kid);
        sb.append(", time=").append(time);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}