package com.lewis.base.entity;

import java.io.Serializable;

public class Stucent implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stucent.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stucent.account
     *
     * @mbg.generated
     */
    private String account;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stucent.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stucent.pic
     *
     * @mbg.generated
     */
    private String pic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stucent.phone
     *
     * @mbg.generated
     */
    private String phone;
    private Srecord srecord;

    public Srecord getSrecord() {
        return srecord;
    }

    public void setSrecord(Srecord srecord) {
        this.srecord = srecord;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stucent.banji
     *
     * @mbg.generated
     */
    private String banji;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table stucent
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stucent.id
     *
     * @return the value of stucent.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stucent.id
     *
     * @param id the value for stucent.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stucent.account
     *
     * @return the value of stucent.account
     *
     * @mbg.generated
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stucent.account
     *
     * @param account the value for stucent.account
     *
     * @mbg.generated
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stucent.name
     *
     * @return the value of stucent.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stucent.name
     *
     * @param name the value for stucent.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stucent.pic
     *
     * @return the value of stucent.pic
     *
     * @mbg.generated
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stucent.pic
     *
     * @param pic the value for stucent.pic
     *
     * @mbg.generated
     */
    public void setPic(String pic) {
        this.pic = pic == null ? null : pic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stucent.phone
     *
     * @return the value of stucent.phone
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stucent.phone
     *
     * @param phone the value for stucent.phone
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stucent.banji
     *
     * @return the value of stucent.banji
     *
     * @mbg.generated
     */
    public String getBanji() {
        return banji;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stucent.banji
     *
     * @param banji the value for stucent.banji
     *
     * @mbg.generated
     */
    public void setBanji(String banji) {
        this.banji = banji == null ? null : banji.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stucent
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", account=").append(account);
        sb.append(", name=").append(name);
        sb.append(", pic=").append(pic);
        sb.append(", phone=").append(phone);
        sb.append(", banji=").append(banji);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}