package com.lewis.base.mapper;

import com.lewis.base.entity.Kecheng;
import java.util.List;

public interface KechengMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kecheng
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kecheng
     *
     * @mbg.generated
     */
    int insert(Kecheng record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kecheng
     *
     * @mbg.generated
     */
    Kecheng selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kecheng
     *
     * @mbg.generated
     */
    List<Kecheng> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kecheng
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Kecheng record);

    List<Kecheng> getKcList(Kecheng kecheng);
}