package com.lewis.base.mapper;

import com.lewis.base.entity.Stucent;
import java.util.List;

public interface StucentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stucent
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stucent
     *
     * @mbg.generated
     */
    int insert(Stucent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stucent
     *
     * @mbg.generated
     */
    Stucent selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stucent
     *
     * @mbg.generated
     */
    List<Stucent> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stucent
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Stucent record);
}