package com.lewis.base.mapper;

import com.lewis.base.entity.Tercher;
import java.util.List;

public interface TercherMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tercher
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tercher
     *
     * @mbg.generated
     */
    int insert(Tercher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tercher
     *
     * @mbg.generated
     */
    Tercher selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tercher
     *
     * @mbg.generated
     */
    List<Tercher> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tercher
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Tercher record);

    Tercher check(String account);

    Tercher login(Tercher tercher);
}